/* test_main.c -- SIL cross-validation harness.
 *
 * Replays the CSV test vectors generated by
 * python/scripts/generate_c_test_vectors.py through the C
 * implementation and reports max absolute error against the Python
 * reference outputs recorded in those same files.
 *
 * Build: see c/Makefile.  Run: ./build/test_main
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

#include "eskf.h"
#include "control.h"
#include "quat_math.h"

#define MAX_LINE 4096

static int read_row(FILE *f, double *vals, int n) {
    char line[MAX_LINE];
    if (!fgets(line, sizeof(line), f)) return 0;
    char *tok = strtok(line, ",\n");
    int i = 0;
    while (tok && i < n) {
        vals[i++] = atof(tok);
        tok = strtok(NULL, ",\n");
    }
    return i == n;
}

static void skip_header(FILE *f) {
    char line[MAX_LINE];
    if (fgets(line, sizeof(line), f) == NULL) {
        /* empty file; downstream read_row will simply return 0 */
    }
}

/* -------------------------------------------------------------- predict */

static int test_eskf_predict(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) { printf("FAIL  cannot open %s\n", path); return 1; }
    skip_header(f);

    ESKF kf;
    double p0[3] = {0, 0, -8000.0}, v0[3] = {160.0, 0, 0}, q0[4];
    quat_from_euler(0, -0.05, 0.02, q0);
    eskf_init(&kf, p0, v0, q0, 5.0, 1.0, 2.0 * M_PI / 180.0,
             0.5 * M_PI / 180.0, 0.1);

    double vals[7 + 3 + 3 + 4 + 3 + 3 + 15];
    int n = 7 + 3 + 3 + 4 + 3 + 3 + 15;
    double max_pos_err = 0, max_vel_err = 0, max_q_err = 0, max_P_err = 0;
    int rows = 0;

    while (read_row(f, vals, n)) {
        double f_meas[3] = {vals[0], vals[1], vals[2]};
        double w_meas[3] = {vals[3], vals[4], vals[5]};
        double dt = vals[6];
        eskf_predict(&kf, f_meas, w_meas, dt);

        const double *p_ref = &vals[7];
        const double *v_ref = &vals[10];
        const double *q_ref = &vals[13];
        const double *bg_ref = &vals[17];
        const double *ba_ref = &vals[20];
        const double *P_ref = &vals[23];
        (void)bg_ref; (void)ba_ref;

        for (int i = 0; i < 3; i++) {
            double e = fabs(kf.state.p[i] - p_ref[i]);
            if (e > max_pos_err) max_pos_err = e;
            e = fabs(kf.state.v[i] - v_ref[i]);
            if (e > max_vel_err) max_vel_err = e;
        }
        for (int i = 0; i < 4; i++) {
            double e = fabs(kf.state.q[i] - q_ref[i]);
            if (e > max_q_err) max_q_err = e;
        }
        for (int i = 0; i < 15; i++) {
            double e = fabs(kf.P[i][i] - P_ref[i]);
            if (e > max_P_err) max_P_err = e;
        }
        rows++;
    }
    fclose(f);

    printf("  eskf_predict  rows=%d  max|dpos|=%.3e m  max|dvel|=%.3e m/s  "
          "max|dq|=%.3e  max|dPdiag|=%.3e\n",
          rows, max_pos_err, max_vel_err, max_q_err, max_P_err);

    int ok = max_pos_err < 1e-6 && max_vel_err < 1e-6 &&
            max_q_err < 1e-9 && max_P_err < 1e-6;
    printf("%s  test_eskf_predict\n", ok ? "PASS" : "FAIL");
    return ok ? 0 : 1;
}

/* --------------------------------------------------------------- update */

static int test_eskf_update(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) { printf("FAIL  cannot open %s\n", path); return 1; }
    skip_header(f);

    ESKF kf;
    double p0[3] = {0, 0, -8000.0}, v0[3] = {160.0, 0, 0}, q0[4];
    quat_from_euler(0, -0.05, 0.0, q0);
    eskf_init(&kf, p0, v0, q0, 8.0, 1.0, 2.0 * M_PI / 180.0,
             0.5 * M_PI / 180.0, 0.1);

    /* fx,fy,fz,wx,wy,wz,dt,update_type(1),
       posx,posy,posz,velx,vely,velz,alt(7),
       p(3),v(3),q(4),bg(3),ba(3),Pdiag(15) = 7+1+7+3+3+4+3+3+15 = 46 */
    int n = 7 + 1 + 7 + 3 + 3 + 4 + 3 + 3 + 15;
    double vals[64];
    double max_pos_err = 0, max_vel_err = 0, max_P_err = 0;
    int rows = 0;

    while (read_row(f, vals, n)) {
        double f_meas[3] = {vals[0], vals[1], vals[2]};
        double w_meas[3] = {vals[3], vals[4], vals[5]};
        double dt = vals[6];
        int update_type = (int)vals[7];
        double pos_meas[3] = {vals[8], vals[9], vals[10]};
        double vel_meas[3] = {vals[11], vals[12], vals[13]};
        double alt_meas = vals[14];

        eskf_predict(&kf, f_meas, w_meas, dt);
        if (update_type == 1) {
            double pos_std[3] = {1.5, 1.5, 3.0};
            eskf_update_gnss(&kf, pos_meas, vel_meas, pos_std, 0.1);
        } else if (update_type == 2) {
            eskf_update_baro(&kf, alt_meas, 1.0);
        }

        const double *p_ref = &vals[15];
        const double *v_ref = &vals[18];
        const double *P_ref = &vals[31];

        for (int i = 0; i < 3; i++) {
            double e = fabs(kf.state.p[i] - p_ref[i]);
            if (e > max_pos_err) max_pos_err = e;
            e = fabs(kf.state.v[i] - v_ref[i]);
            if (e > max_vel_err) max_vel_err = e;
        }
        for (int i = 0; i < 15; i++) {
            double e = fabs(kf.P[i][i] - P_ref[i]);
            if (e > max_P_err) max_P_err = e;
        }
        rows++;
    }
    fclose(f);

    printf("  eskf_update   rows=%d  max|dpos|=%.3e m  max|dvel|=%.3e m/s  "
          "max|dPdiag|=%.3e\n", rows, max_pos_err, max_vel_err, max_P_err);

    int ok = max_pos_err < 1e-5 && max_vel_err < 1e-5 && max_P_err < 1e-5;
    printf("%s  test_eskf_update\n", ok ? "PASS" : "FAIL");
    return ok ? 0 : 1;
}

/* -------------------------------------------------------------- control */

static int test_control(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) { printf("FAIL  cannot open %s\n", path); return 1; }
    skip_header(f);

    PitchAttitudeHold ctrl;
    pitch_hold_default_gains(&ctrl.gains);
    ctrl.de_trim_deg = 10.28;

    double vals[4];
    double max_err = 0;
    int rows = 0;
    while (read_row(f, vals, 4)) {
        double aero_cmd[6];
        pitch_hold_command(&ctrl, vals[0], vals[1], vals[2], aero_cmd);
        double e = fabs(aero_cmd[1] - vals[3]);
        if (e > max_err) max_err = e;
        rows++;
    }
    fclose(f);

    printf("  control       rows=%d  max|de_err|=%.3e deg\n", rows, max_err);
    int ok = max_err < 1e-9;
    printf("%s  test_control\n", ok ? "PASS" : "FAIL");
    return ok ? 0 : 1;
}

int main(int argc, char **argv) {
    const char *vecdir = (argc > 1) ? argv[1] : "test_vectors";
    char path[512];
    int failures = 0;

    printf("SIL cross-validation: C implementation vs. Python reference\n");
    printf("=============================================================\n");

    snprintf(path, sizeof(path), "%s/eskf_predict_vectors.csv", vecdir);
    failures += test_eskf_predict(path);

    snprintf(path, sizeof(path), "%s/eskf_update_vectors.csv", vecdir);
    failures += test_eskf_update(path);

    snprintf(path, sizeof(path), "%s/control_vectors.csv", vecdir);
    failures += test_control(path);

    printf("=============================================================\n");
    if (failures == 0) {
        printf("ALL SIL CROSS-VALIDATION TESTS PASSED\n");
    } else {
        printf("%d TEST GROUP(S) FAILED\n", failures);
    }
    return failures == 0 ? 0 : 1;
}
